import { writeFile } from "node:fs/promises";
import { fileURLToPath, pathToFileURL } from "node:url";

import {
  ACTIVITY_GENERATOR_IDS,
  ACTIVITY_IDS,
  ANSWER_LAYOUT_IDS,
  DIALOGUE_IDS,
  EFFECT_PRESET_IDS,
  GENERATOR_IDS,
  ICON_IDS,
  MANIPULATIVE_IDS,
  SCENE_IDS,
} from "../../packages/contracts/src/index.js";

const OUTPUT_URL = new URL("../../src/content/generated/content_contract_v1.gd", import.meta.url);

const BAND_IDS = ["intro", "practice", "challenge"] as const;
const VALIDATION_SEEDS = [1, 7, 42, 20260721] as const;

const STRING_LISTS = {
  ACTIVITY_IDS,
  GENERATOR_IDS,
  MANIPULATIVE_IDS,
  ANSWER_LAYOUT_IDS,
  SCENE_IDS,
  EFFECT_PRESET_IDS,
  ICON_IDS,
  DIALOGUE_IDS,
  BAND_IDS,
  FORBIDDEN_OBJECT_KEYS: ["__proto__", "prototype", "constructor"],
  REQUIRED_PACKAGE_KEYS: [
    "schema_version",
    "content_version",
    "activity_id",
    "localizations",
    "icon_id",
    "scene_id",
    "run",
    "difficulty_bands",
    "validation_samples",
    "checksum",
  ],
  OPTIONAL_PACKAGE_KEYS: ["adaptive_policy"],
  LOCALIZATION_ROOT_KEYS: ["ko-KR"],
  LOCALIZATION_KEYS: ["title", "description", "tutorial_steps"],
  RUN_KEYS: [
    "starting_hearts",
    "goal",
    "timer",
    "rewards",
    "combo_thresholds",
    "boss_every_correct",
    "effects",
  ],
  GOAL_KEYS: ["kind", "target"],
  TIMER_KEYS: ["enabled", "seconds", "profile_can_disable"],
  REWARDS_KEYS: ["apples_per_correct", "completion_apples"],
  EFFECT_KEYS: ["correct", "wrong", "combo", "boss", "level_up", "reward", "health_loss"],
  BAND_KEYS: ["band_id", "generator_id", "generator_parameters", "answer_layout", "manipulative"],
  ANSWER_LAYOUT_REQUIRED_KEYS: ["id"],
  ANSWER_LAYOUT_OPTIONAL_KEYS: ["options"],
  MANIPULATIVE_KEYS: ["id", "config", "initial_state"],
  ADAPTIVE_POLICY_KEYS: [
    "enabled_by_default",
    "min_band_id",
    "max_band_id",
    "window_size",
    "promote_correctness",
    "demote_correctness",
  ],
  VALIDATION_SAMPLE_KEYS: ["band_id", "seed", "expected_answer"],
  INTEGER_ANSWER_KEYS: ["kind", "value"],
  INTEGER_LIST_ANSWER_KEYS: ["kind", "values", "order_matters"],
  REQUIRED_MANIFEST_KEYS: ["schema_version", "manifest_version", "published_at", "activity_order", "packages"],
  MANIFEST_ENTRY_KEYS: ["activity_id", "content_version", "path", "checksum"],
} as const;

function renderConstStringArray(name: string, values: readonly string[]): string[] {
  return [
    `const ${name} := [`,
    ...values.map((value) => `\t${JSON.stringify(value)},`),
    "]",
  ];
}

function renderActivityGeneratorMap(): string[] {
  return [
    "const ACTIVITY_GENERATOR_IDS := {",
    ...Object.entries(ACTIVITY_GENERATOR_IDS).map(
      ([activityId, generatorId]) => `\t${JSON.stringify(activityId)}: ${JSON.stringify(generatorId)},`,
    ),
    "}",
  ];
}

/** Renders the complete Godot-side schema/allowlist contract without reading workspace state. */
export function renderGodotContentContract(): string {
  const lines = [
    "# Generated by tools/content/export_godot_contract.ts. Do not edit by hand.",
    "class_name ContentContractV1",
    "extends RefCounted",
    "",
    "const SCHEMA_VERSION := 1",
    'const MANIFEST_VERSION := "1.0.0"',
    "const SAFE_INTEGER_MIN := -9007199254740991",
    "const SAFE_INTEGER_MAX := 9007199254740991",
    'const CHECKSUM_PREFIX := "sha256:"',
    "const CHECKSUM_HEX_LENGTH := 64",
    "const MAX_JSON_SOURCE_LENGTH := 2000000",
    "const MAX_JSON_SOURCE_BYTES := 6000000",
    "const MAX_JSON_NESTING := 64",
    "const MAX_TITLE_CODEPOINTS := 80",
    "const MAX_DESCRIPTION_CODEPOINTS := 500",
    "const MAX_TUTORIAL_CODEPOINTS := 240",
    "",
  ];

  for (const [name, values] of Object.entries(STRING_LISTS)) {
    lines.push(...renderConstStringArray(name, values), "");
  }
  lines.push(
    "const VALIDATION_SEEDS := [1, 7, 42, 20260721]",
    "",
    ...renderActivityGeneratorMap(),
    "",
  );
  return lines.join("\n");
}

async function main(): Promise<void> {
  await writeFile(OUTPUT_URL, renderGodotContentContract(), "utf8");
}

const invokedPath = process.argv[1];
if (invokedPath !== undefined && pathToFileURL(invokedPath).href === import.meta.url) {
  await main();
}

export const generatedGodotContractPath = fileURLToPath(OUTPUT_URL);
